-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 1.5 — oauth_accounts.
--
-- Links a User to a provider identity. (provider, providerUserId) is the
-- natural composite key; we also keep an autogenerated cuid for FK targets.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TYPE "OAuthProvider" AS ENUM ('GOOGLE', 'GITHUB');

CREATE TABLE "oauth_accounts" (
  "id"             TEXT PRIMARY KEY,
  "userId"         TEXT NOT NULL,
  "provider"       "OAuthProvider" NOT NULL,
  "providerUserId" VARCHAR(255) NOT NULL,
  "providerEmail"  VARCHAR(255),
  "providerHandle" VARCHAR(255),
  "accessToken"    TEXT,
  "refreshToken"   TEXT,
  "expiresAt"      TIMESTAMP(3),
  "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"      TIMESTAMP(3) NOT NULL,
  CONSTRAINT "oauth_accounts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "oauth_accounts_provider_providerUserId_key" UNIQUE ("provider", "providerUserId")
);
CREATE INDEX "oauth_accounts_userId_idx" ON "oauth_accounts" ("userId");

CREATE TRIGGER oauth_accounts_set_updated_at BEFORE UPDATE ON "oauth_accounts"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ───── RLS ──────────────────────────────────────────────────────────────────
-- Same pattern as email_tokens: the OAuth callback flow runs without
-- app.user_id (the user isn't logged in yet), so policies must allow the
-- system-context path.
ALTER TABLE "oauth_accounts" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "oauth_accounts_self_select" ON "oauth_accounts"
  FOR SELECT
  USING (current_app_user_id() IS NULL OR "userId" = current_app_user_id());

CREATE POLICY "oauth_accounts_insert" ON "oauth_accounts"
  FOR INSERT
  WITH CHECK (current_app_user_id() IS NULL OR "userId" = current_app_user_id());

CREATE POLICY "oauth_accounts_update" ON "oauth_accounts"
  FOR UPDATE
  USING (current_app_user_id() IS NULL OR "userId" = current_app_user_id())
  WITH CHECK (current_app_user_id() IS NULL OR "userId" = current_app_user_id());

CREATE POLICY "oauth_accounts_delete" ON "oauth_accounts"
  FOR DELETE
  USING (current_app_user_id() IS NULL OR "userId" = current_app_user_id());
